### PR TITLE
Added New Section

### PR DESCRIPTION
**Pull request by Formdude**
Added new section regarding increasing the total amount of ram you have and installing 64 bit java. Please let me know if you have any comments, or concerns regarding this.

### CODE REVIEW

**Comment by Column01** [comment]
Only suggestion is adding more info on how to increase FPS. Such as adding Fastcraft/BetterFPS and as well as adding FoamFix if modpacks do not already have it for 1.10+

**Comment by Formdude** [comment]
I can begin work on that, I was also discussing adding all of the launchers instead of just the mym launcher.

**Comment by Column01** [comment]
Those ideas sound good! tag me when you are done and ready for this to be added to the wiki :D

**Comment by Column01** [comment]
@Formdude I know you're busy with school but I thought I tag you to remind you of this PR. Any chance these suggestions could be added?

**Comment by Formdude** [comment]
You happened to post this after my last exam actually, this will be done as soon as I get home :)

**Comment by Column01** [comment]
Looks like the last commit has no changes. Did you get a chance to add anything and forget to commit it?

**Comment by Column01** [comment]
@Formdude Are there any changes you'd like to add? I can help if need be.

**Comment by Formdude** [comment]
Whispered in slack about it column ^^

**Comment by Aiidoneus** [comment]
Status on this?

**Comment by Formdude** [comment]
Hello, added a new section but I'm not sure why the build failed. Can someone look at the code to see what went wrong?

**Comment by Formdude** [comment]
Never mind, the build seems to work when I launched it, I could even navigate to the section that I changed. Not sure why it says that all checks have failed, maybe I need to remake the fork of my wiki.

**Pull request merged**
